import React from 'react';
import Head from 'next/head';

function HeadComponent() {
  return (
    <Head>
      <title>Na přednášku</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/naPrednaskuIco.png" />
    </Head>
  );
}

export default HeadComponent;
